image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: masatma1
  APP_NAME: hotel-service
  REPO: SWA-hotel

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.fel.cvut.cz/masatma1/swa-pet-hotel .
    - docker push registry.gitlab.fel.cvut.cz/masatma1/swa-pet-hotel