INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, GENDER) VALUES (100001, 'Jan', 'Novak', 'M');
INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, GENDER) VALUES (100002, 'Petr', 'Skocdopole', 'M');
INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, GENDER) VALUES (100003, 'Martina', 'Dvorakova', 'F');
INSERT INTO CUSTOMER(ID, FIRST_NAME, LAST_NAME, GENDER) VALUES (100004, 'Test', 'Test', 'O');